music.setTempo(151)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Double))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(698, music.beat(BeatFraction.Double))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(698, music.beat(BeatFraction.Breve))
basic.pause(100)
music.playTone(440, music.beat(BeatFraction.Half))
basic.pause(100)
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(50)
music.playTone(349, music.beat(BeatFraction.Breve))
